import type { ParkingLocation } from '@/types';

export const parkingLocations: ParkingLocation[] = [
  {
    id: '1',
    name: 'New Road Parking Complex',
    address: 'New Road Gate, Kathmandu',
    coords: { lat: 27.704, lng: 85.313 },
    availability: {
      twoWheeler: { total: 200, available: 45 },
      fourWheeler: { total: 50, available: 5 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '2',
    name: 'Durbarmarg Secure Park',
    address: 'Opposite Hotel Annapurna, Durbarmarg',
    coords: { lat: 27.712, lng: 85.318 },
    availability: {
      twoWheeler: { total: 100, available: 10 },
      fourWheeler: { total: 30, available: 2 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '3',
    name: 'Thamel Bike Station',
    address: 'Saat Ghumti, Thamel',
    coords: { lat: 27.717, lng: 85.311 },
    availability: {
      twoWheeler: { total: 350, available: 120 },
      fourWheeler: { total: 0, available: 0 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '4',
    name: 'Lalitpur Central Parking',
    address: 'Pulchowk, Lalitpur',
    coords: { lat: 27.683, lng: 85.318 },
    availability: {
      twoWheeler: { total: 150, available: 70 },
      fourWheeler: { total: 40, available: 15 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '5',
    name: 'Bhat-Bhateni Supermarket Park',
    address: 'Bhat-Bhateni, Naxal',
    coords: { lat: 27.718, lng: 85.328 },
    availability: {
      twoWheeler: { total: 500, available: 250 },
      fourWheeler: { total: 100, available: 30 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '6',
    name: 'Basantapur Square Parking',
    address: 'Basantapur Durbar Square Area',
    coords: { lat: 27.704, lng: 85.307 },
    availability: {
      twoWheeler: { total: 80, available: 15 },
      fourWheeler: { total: 10, available: 1 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '7',
    name: 'Kalanki Car Stop',
    address: 'Kalanki Chowk, Ring Road',
    coords: { lat: 27.696, lng: 85.281 },
    availability: {
      twoWheeler: { total: 120, available: 30 },
      fourWheeler: { total: 60, available: 10 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '8',
    name: 'Koteshwor Multi-Level Park',
    address: 'Near Koteshwor Chowk',
    coords: { lat: 27.680, lng: 85.345 },
    availability: {
      twoWheeler: { total: 250, available: 80 },
      fourWheeler: { total: 80, available: 20 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '9',
    name: 'Jawalakhel Community Parking',
    address: 'Jawalakhel, Lalitpur',
    coords: { lat: 27.675, lng: 85.316 },
    availability: {
      twoWheeler: { total: 100, available: 40 },
      fourWheeler: { total: 20, available: 5 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '10',
    name: 'Civil Mall Underground Parking',
    address: 'Sundhara, Kathmandu',
    coords: { lat: 27.701, lng: 85.312 },
    availability: {
      twoWheeler: { total: 400, available: 150 },
      fourWheeler: { total: 120, available: 25 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '11',
    name: 'Gongabu Bus Park Lot',
    address: 'New Bus Park, Gongabu',
    coords: { lat: 27.737, lng: 85.314 },
    availability: {
      twoWheeler: { total: 300, available: 100 },
      fourWheeler: { total: 50, available: 15 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '12',
    name: 'Patan Dhoka Public Parking',
    address: 'Near Patan Dhoka, Lalitpur',
    coords: { lat: 27.676, lng: 85.321 },
    availability: {
      twoWheeler: { total: 180, available: 90 },
      fourWheeler: { total: 35, available: 8 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '13',
    name: 'Boudha Stupa Parking Area',
    address: 'Boudhanath, Kathmandu',
    coords: { lat: 27.721, lng: 85.362 },
    availability: {
      twoWheeler: { total: 220, available: 60 },
      fourWheeler: { total: 40, available: 12 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '14',
    name: 'Maharajgunj Wheel Stop',
    address: 'Tribhuvan University Teaching Hospital Area',
    coords: { lat: 27.735, lng: 85.326 },
    availability: {
      twoWheeler: { total: 150, available: 55 },
      fourWheeler: { total: 50, available: 18 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '15',
    name: 'Balaju Industrial Park & Ride',
    address: 'Balaju Industrial District',
    coords: { lat: 27.731, lng: 85.299 },
    availability: {
      twoWheeler: { total: 100, available: 35 },
      fourWheeler: { total: 70, available: 25 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '16',
    name: 'Sankhamul Riverside Parking',
    address: 'Sankhamul, Kathmandu',
    coords: { lat: 27.684, lng: 85.333 },
    availability: {
      twoWheeler: { total: 90, available: 45 },
      fourWheeler: { total: 20, available: 9 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '17',
    name: 'Tinkune Open Lot',
    address: 'Tinkune, Subidhanagar',
    coords: { lat: 27.688, lng: 85.347 },
    availability: {
      twoWheeler: { total: 200, available: 110 },
      fourWheeler: { total: 50, available: 22 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '18',
    name: 'Maitidevi Temple Parking',
    address: 'Maitidevi, Kathmandu',
    coords: { lat: 27.708, lng: 85.334 },
    availability: {
      twoWheeler: { total: 70, available: 28 },
      fourWheeler: { total: 15, available: 4 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
  {
    id: '19',
    name: 'Chabahil Chowk Park',
    address: 'Near Chabahil Stupa',
    coords: { lat: 27.719, lng: 85.349 },
    availability: {
      twoWheeler: { total: 130, available: 60 },
      fourWheeler: { total: 30, available: 7 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: false,
  },
  {
    id: '20',
    name: 'Bhaktapur Durbar Parking',
    address: 'Bhaktapur Durbar Square Entrance',
    coords: { lat: 27.672, lng: 85.428 },
    availability: {
      twoWheeler: { total: 250, available: 100 },
      fourWheeler: { total: 60, available: 15 },
    },
    image: 'https://placehold.co/600x400.png',
    isMonthly: true,
  },
];
